project_id = "edem-25-26-mimove"
region     = "europe-west1"
zone       = "europe-west1-b"
subnetwork = "projects/edem-25-26-mimove/regions/europe-west1/subnetworks/default"
service_account_email = "563176013731-compute@developer.gserviceaccount.com"